version: '3'

services:
  kyopro:
    container_name: tools
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /workspace
    volumes:
      - ../.acc:/root/.config/atcoder-cli-nodejs
      - ..:/workspace
